#!/bin/bash

if [ ! -f /config/redis.conf ]; then
  cp /defaults/redis.conf /config/redis.conf
  chown abc:abc /config/redis.conf && chmod 774 /config/redis.conf
fi

sed 's/^daemonize yes/daemonize no/' -i /etc/redis/redis.conf
sed 's/^bind 127.0.0.1/bind 0.0.0.0/' -i /etc/redis/redis.conf

exec /sbin/setuser abc redis-server /config/redis.conf
